### PR TITLE
[DO NOT MERGE] Initial re-skin of provisioning mode HTML assets

### PR DESCRIPTION
**Pull request by sandeepmistry**
Based on the files provided by @ErnestoELC with some modifications.

Here's some screenshots from OS X and iOS:

screen shot 2016-12-20 at 2 20 03 pm

img_1430

cc/ @cmaglie

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Let's hold off merging this until we get feedback on the design of the page from Laura ...

**Comment by sandeepmistry** [comment]
Feedback from @balboal (Laura):

> Hey Sandeep, I think it looks ok, I only wonder about the button, I couldn't get it to work in the Arduino css styling, check the bottom of this page as an example https://resellers.arduino.cc/homepage/genuino-micro It is mainly the hover and the press down states that are missing is it possible to make? Otherwise we could go with the version you shared me. :

**Comment by agdl** [comment]
@sandeepmistry please reapply this on the new firmware 19.5.2

**Comment by sandeepmistry** [comment]
I've updated with the feedback from @balboal in https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/pull/4#issuecomment-270645201.

Here are some screenshots:

img_1511
screen shot 2017-03-09 at 5 50 38 pm
screen shot 2017-03-09 at 5 50 33 pm


@agdl @akash73 what do you think of the changes to the styling and text changes in the instructions.

**Comment by akash73** [comment]
LGTM !

**Pull request merged**
